apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-deal-recommender
  labels:
    app: fashion-deal-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fashion-deal-recommender
  template:
    metadata:
      labels:
        app: fashion-deal-recommender
    spec:
      containers:
      - name: fashion-deal-recommender
        image: fashion-deal-recommender:latest
        ports:
        - containerPort: 3000
        env:
        - name: SCRAPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: scraper-api-secret
              key: api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
